version: '2.2'

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - oauth2-proxy
      - backend
  
  oauth2-proxy:
    image: quay.io/pusher/oauth2_proxy:v3.2.0
    command: -config=/etc/oauth2-proxy.cfg --set-xauthrequest
    volumes:
      - ./oauth2-proxy/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
  
  backend:
    image: oauth2-backend
    build: backend
    command: npm run start
    